### ISSUE TITLE
Wheels are not compatible with Cinema 4D 2023.2 (Python 3.10)

### ISSUE THREAD

**Issue by Shivamist** [danbradham/wheels#1]
Since Maxon decided to do an update in the latest (2023.2) version, the wheels are not compatible anymore. 
I'm willing to contribute to this repo but i lack the knowledge to build the .whl files. Could you point me in the right direction ?
Thanks in advance :)

**Comment by AntonWangle** [comment]
I am also facing this issue. Any hints are appreciated.

**Comment by danbradham** [comment]
Sorry guys, I've been in the middle of a few projects at work. I'm unsure when I can get around to this. The process for building these wheels with non-standard releases of python suuuucks. When I have time I'll try to create some build scripts or instructions this time around. I'm hopeful that when our software shifts to PySide6 this process will become easier.

**Comment by danbradham** [comment]
Some progress on this in #2, thanks to @blockinhead.

If you guys want to download those wheels immediately and try them out please do so. I'll be testing them out and will merge when I verify the wheels are working properly.

**Comment by danbradham** [comment]
Closed by #2

**Comment by Shivamist** [comment]
I'm encountering this issue when trying the new release :
![image](https://github.com/danbradham/wheels/assets/95488155/a63b2584-fb21-47d8-86de-a21ad8e4a9e6)

Atm i'm using pip 20.2.3 and it's loaded this way : 
![image](https://github.com/danbradham/wheels/assets/95488155/9621b6e9-6a27-4fb4-8f36-70fb154d8384)


I'm quite lost since it seems to work for you guys, how are you installing these wheels? Thanks for your time :)

**Comment by danbradham** [comment]
What platform are you on?

**Comment by Shivamist** [comment]
I'm on Windows 10, but i've just managed a few minutes ago to install the wheels via a newer version of pip installed directly inside Cinema 4D (via the get-pip.py method).
![image](https://github.com/danbradham/wheels/assets/95488155/46f16e71-bd47-4018-afce-47ddad1080b6)

**Comment by danbradham** [comment]
Nice, glad it's working for you.
